### ISSUE TITLE
[ui] chat 뷰 구현

### ISSUE THREAD

**Issue by jihyunniiii** [SOPT-32ND-APP4-Karrot/Carrot_AOS#10]
## *To-do*
- [x] top app bar 구현
- [x] extended app bar 구현 (거래 관련 부분)
- [x] 채팅 리사이클러뷰 구현
- [x] 채팅 리사이클러뷰 관련 아이템 구현 (left chat, right chat, announcement)
- [x] bottom app bar 구현 (채팅 입력 창)
