### ISSUE TITLE
[ui] review 뷰 구현

### ISSUE THREAD

**Issue by jihyunniiii** [SOPT-32ND-APP4-Karrot/Carrot_AOS#12]
## *To-do*
- [x] top app bar 구현
- [x] 후기 관련 리사이클러뷰 구현
- [x] 리사이클러뷰 아이템 구현 (title, card, button)
