### ISSUE TITLE
[feat] chat 뷰 기능 개발

### ISSUE THREAD

**Issue by jihyunniiii** [SOPT-32ND-APP4-Karrot/Carrot_AOS#14]
## *To-do*
- [x] top app bar 뒤로 가기 버튼 기능 구현
- [x] extended app bar 거래 후기 버튼 기능 구현
- [x] 채팅 리사이클러뷰 기능 구현
- [x] 메시지 보내기 editText에 텍스트 입력 시 전송 버튼 색 변경 로직 구현
- [x] 메시지 전송 로직 구현
- [x] 채팅 API 연결
