### ISSUE TITLE
[feat] chat 뷰, review 뷰 최종 마무리

### ISSUE THREAD

**Issue by jihyunniiii** [SOPT-32ND-APP4-Karrot/Carrot_AOS#20]
## *To-do*
- [ ] chat 뷰 매너 온도 설정
- [ ] chat 뷰 키보드 올라올 때 화면 설정
- [x] review 뷰 user nickname 설정
