### ISSUE TITLE
[ui] sale 뷰 디자인

### ISSUE THREAD

**Issue by l2zh** [SOPT-32ND-APP4-Karrot/Carrot_AOS#4]
## *To-do*
- [x] 리사이클러뷰 아이템, 전체적인 뷰 디자인
- [x] 리사이클러뷰 더미 데이터로 연결해보기
- [x] top app bar
- [x] progress bar 디자인

**Comment by wateralsie** [comment]
굳굳👍 이슈 assignee는 자기자신만 해주면 됩니당~
