### ISSUE TITLE
[feat] bottom navigation 로직 구현

### ISSUE THREAD

**Issue by wateralsie** [SOPT-32ND-APP4-Karrot/Carrot_AOS#5]
## *To-do*
- [x] 아이콘 5개 selector drawable 파일 생성
- [x] 바텀내비 메뉴 구성
- [x] 홈뷰 포함 5개의 fragment 생성
- [x] navigation 컴포넌트 사용하여 바텀내비 기능 구현
