### ISSUE TITLE
[ui] 버튼 default 스타일 지정

### ISSUE THREAD

**Issue by wateralsie** [SOPT-32ND-APP4-Karrot/Carrot_AOS#7]
## *To-do*
- [x] 기본 패딩 제거
- [x] background transparent 설정
- [x] 위를 적용한 style을 themes에 넣기
